### PR TITLE
HTML Form

### PR DESCRIPTION
**Pull request by rukundoeric**
### What does this do? 
* Collect User Data
### Description of Task to be completed? 
* A structural clone of the intuit's signup page
### How should this be manually tested? 
* Clone this repo https://github.com/rukundoeric/html-form.git
* Navigate to project directory.
* If you have a live server in you vs-code, just run it.
* Otherwise just open the index page with your browser.

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Requested.

## :clap: :clap: :clapl: AWESOME! the page looks like the original even with the effects!!!

I liked that even if it wasn't required you use JS for effects!. Also, notice you use Sass for the CSS, that was nice! :sunglasses: 

Other things to notice:
:100: Improved readability with 2 space indentation.
:100: Use of semantic HTML for main sections and form elements
:100: Use complementary technologies like Sass and JS. 
:100: README descriptive enough
:100: Pull Request message is descriptive

### [Mandatory]

- [x] Project not passing all Linter Checks

- [x] The header should be outside the main container

- [x] The footer should be outside the main container

- [x] Upload only the files needed for the project or add them to ```.gitignore```.
image

### [OPTIONAL]

- [x] The warning is appearing even if the form hasn't been filled. It would be great to fix it.
image

- [x] Remove JS from HTML and assign it to its own file and directory.

- [x] Move the images from root to the ```img``` directory.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer: !!!

**Comment by rukundoeric** [comment]
I would like to thank you for the time you took to review our project, and I would like to inform you that we implemented all of them except ofcourse ignoring scss folder Because our linter is confured to check `.scss` files instead of  `.css`  as it is mentioned [Here](https://github.com/microverseinc/linters-config/tree/master/html-css), in case we decide to use scss instead of css.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x] Please use form tag for the form section

- [x] Please make sure the bottom of each input section has a disclaimer text that matches the context and style of the original page

- [x] **Optional** Add description within 1-2 lines about your project in about section
chrome-capture (4)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by arslanbisharat — APPROVED** [review]
### Congratulations APPROVED :clap:
Hello, I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] Please update the app on the deploy side because everything is not updated on the site you provided in the readme as a live version. 
chrome-capture (5)


_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Pull request merged**
